### ISSUE TITLE
Fails to compile on Debian 

### ISSUE THREAD

**Issue by ttepatti** [intrepidcs/icsscand#1]
Hello!

I'm trying to compile this library to be able to use the [Intrepid SocketCAN kernel module](https://github.com/intrepidcs/intrepid-socketcan-kernel-module). Per the README for that project: "Once the module is built and loaded run icsscand to turn on SocketCAN support."

So that lead me here to compile icsscand, whose README led to me compiling the libicsneoapi libraries. After running the make command for the libraries and copying them to the appropriate system-wide folders, I cloned the icsscand repo and attempted to make it, but received this error:

> gcc -g -c -O2 icsscand.c
> icsscand.c: In function ‘probe_new_devices’:
> icsscand.c:348:40: error: ‘NEODEVICE_ALL’ undeclared (first use in this function); did you mean ‘NEODEVICE_FLEX’?
>          int ret = icsneoFindNeoDevices(NEODEVICE_ALL & NEODEVICE_RADGALAXY, detected, &num_devices);
>                                         ^~~~~~~~~~~~~
>                                         NEODEVICE_FLEX
> icsscand.c:348:40: note: each undeclared identifier is reported only once for each function it appears in
> icsscand.c:399:22: error: ‘NEODEVICE_PLASMA_1_11’ undeclared (first use in this function); did you mean ‘NEODEVICE_PLASMA’?
>                  case NEODEVICE_PLASMA_1_11:
>                       ^~~~~~~~~~~~~~~~~~~~~
>                       NEODEVICE_PLASMA
> icsscand.c:400:22: error: ‘NEODEVICE_PLASMA_1_12’ undeclared (first use in this function); did you mean ‘NEODEVICE_PLASMA_1_11’?
>                  case NEODEVICE_PLASMA_1_12:
>                       ^~~~~~~~~~~~~~~~~~~~~
>                       NEODEVICE_PLASMA_1_11
> icsscand.c:401:22: error: ‘NEODEVICE_PLASMA_1_13’ undeclared (first use in this function); did you mean ‘NEODEVICE_PLASMA_1_12’?
>                  case NEODEVICE_PLASMA_1_13:
>                       ^~~~~~~~~~~~~~~~~~~~~
>                       NEODEVICE_PLASMA_1_12
> icsscand.c:402:22: error: ‘NEODEVICE_ION_2’ undeclared (first use in this function); did you mean ‘NEODEVICE_ION’?
>                  case NEODEVICE_ION_2:
>                       ^~~~~~~~~~~~~~~
>                       NEODEVICE_ION
> icsscand.c:403:22: error: ‘NEODEVICE_ION_3’ undeclared (first use in this function); did you mean ‘NEODEVICE_ION_2’?
>                  case NEODEVICE_ION_3:
>                       ^~~~~~~~~~~~~~~
>                       NEODEVICE_ION_2
> Makefile:13: recipe for target 'icsscand.o' failed
> make: *** [icsscand.o] Error 1

This error appears to stem from the probe_new_devices() function, specifically the nicely-commented line "find all the connected devices."

A bit of background:
- The hardware I'm using is the ValueCAN3
- My uname -a: Linux hostname 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux (This machine is Kali Linux, a distro built on Debian. Normally this is a non-issue in compatibility with Debian-based software, but I figured it should be noted just in case)

While I appreciate the amazing support for the ValueCAN3 on Windows with the VehicleSpy software, you definitely have to jump through a few hoops to get it all up-and-running on Linux :slightly_smiling_face: 

Thanks for your help!

**Comment by davidadley** [comment]
The [latest commit](https://github.com/intrepidcs/icsneoapi/commit/694bf94eeaed933aabc6ea417be5d1cfe32d06a1) to `icsneoapi` broke this package as it removed those declarations from the header files.

Run `git checkout 9c27f83` in `~/intrepidcs/icsneoapi` than follow instruction to build `isoneoapi`.

**Comment by hollinsky-intrepid** [comment]
With version 2.0.0 being a rewrite, we should be clear of this issue. Sorry it was left open this long!
