### ISSUE TITLE
ValueCAN 4-4 not running on Linux

### ISSUE THREAD

**Issue by chste** [intrepidcs/icsscand#16]
We are using the ValueCAN 4-4 network interface device and have problems to get it running on a Linux Machine. We tried with the driver for the ValueCAN 4-2 and we can see the 4 CAN ports using socketCAN, but we cannot get any data from the ports.

**Comment by kschwarz-intrepidcs** [comment]
Can you please provide:
- icsscand & intrepid-socketcan-kernel-module versions used
- steps to reproduce the issue
- distribution specifics
- device firmware versions

Can you also confirm that you set the interface to up (step 11, `sudo ip link set can0 up`)?

**Comment by chste** [comment]
Kernel module version
![grafik](https://github.com/intrepidcs/icsscand/assets/68187581/35f72e7e-0b4f-4995-9e48-0874c6c72d13)

icsscand version
![grafik](https://github.com/intrepidcs/icsscand/assets/68187581/75f621b7-9ffb-44c9-8e60-0f41391b3976)

Steps to reproduce error: follow the instructions on https://intrepidcs.com/socketcan-vcan4/

Distribution
![grafik](https://github.com/intrepidcs/icsscand/assets/68187581/545dfd58-d38f-4059-8e84-40924e07a05a)

Device firmware version will be provided later

**Comment by kschwarz-intrepidcs** [comment]
Thank you for providing this info, can you please try updating icsscand and the kermel module to 3.1.2 and 3.0.4, respectively?

**Comment by chste** [comment]
Thank you, we did a fresh installation on a new machine, with all the latest modules, and with that it works fine. Sorry for the inconvenience.
