### ISSUE TITLE
openDevices can be accessed by 2 threads at the same time

### ISSUE THREAD

**Issue by tysonite** [intrepidcs/icsscand#4]
Does it really safe to access openDevices w/o mutex used in searchForDevices()?

https://github.com/intrepidcs/icsscand/blob/a69c41c9d5df747b73bfcbfe9d0c4991949a0f76/src/main.cpp#L485

**Comment by hollinsky-intrepid** [comment]
This is fixed as of 8d21b98ac61e6ea5ecbc1e3ad8c6241ae531ff64 and release [v2.0.3](https://github.com/intrepidcs/icsscand/releases/tag/v2.0.3)
